### ISSUE TITLE
REQUEST: Language Groups

### ISSUE THREAD

**Issue by MrPavao** [kakaroto/fvtt-module-polyglot#11]
In theory, everyone who speaks Auran can also understand Terran, Ignan, Aquan, and Primordial. Not to mention language groups that are mutually intelligible in homebrews. Could there be a way to add languages to a set so they can be mutually intelligible without losing the flavor of those languages being differently named? Thanks.

**Comment by kakaroto** [comment]
If you can understand the other languages in the same group, then your character should also have those languages as something they understand in their sheet. If they don't, then they don't understand it.
Regardless, polyglot doesn't understand languages or groups or how close one language is to another, it just lists what the system itself is saying it supports, the rest is up to the system and the character sheet to manage.

**Comment by MrPavao** [comment]
I am aware that polyglot doesn't understand languages or groups or how close one language is to another. That's why I made a _feature request_ and not a _bug report_.

If you're not interested in expanding Polyglot's functionality to better match the language system in games including D&D5e and Shadowrun, I would be happy to do it myself. Do you accept pull requests?

**Comment by kakaroto** [comment]
I understood it to be a feature request and not a bug report, but my point was that polyglot shouldn't be the place for that because of how it's designed, it wouldn't make sense. 
I do accept pull requests, but for this, I would most probably reject it and suggest to add the 'language groups' support in the system itself, so if a user selects a group, all the languages belonging to that group would be added to their sheet. It's what makes the most sense to me (also languages and groups are very specific and hardcoded values that will be dependent on the system, so it makes much more sense for the feature to be in the system than in polyglot).
