### ISSUE TITLE
Manage All Languages

### ISSUE THREAD

**Issue by Aquaricat** [kakaroto/fvtt-module-polyglot#17]
Currently, we can use Polyglot to add some custom languages, which is awesome - but I'd love to see the module take the next logical step, and allow *complete control* of the languages available in a campaign.  For example, the world I'm setting up doesn't have any use for gith, so I'd like to be able to remove it from the available list entirely to reduce clutter.

**Comment by kakaroto** [comment]
That will not happen (not by me anyway) because Polyglot is about hiding some texts, not about adding a system independent language manager.
The ability to add 'custom' languages was just because people kept pestering me about it :p I thought of a simple way to do it, but I really don't want to make polyglot more than it currently is.
