### ISSUE TITLE
Everyone understands common

### ISSUE THREAD

**Issue by DeadlyArtist** [kakaroto/fvtt-module-polyglot#55]
Whenever I type something into chat and hear my players saying "Wrong language again!", I painfully realize my NPC doesn't have common as a language, but rather "custom", "any two languages" or similar. This obviously makes it impossible for me to write as the NPC and so I have to manually add common to each and every NPC I make or copy from a compendium.

So my request, please add two things:

1. Every actor has a "common" language in their drop down regardless of whether they actually have it or not.
2. Every actor defaults to "common" or the language that was last used with that actor.

Another workaround would be to just have polyglot default "global" or "unscrambled" instead of "common".

Thank you very much in advance.

**Comment by kakaroto** [comment]
Hi,
1. I can't do that because it defeats the entire purpose of selecting an actor's languages and there ARE some NPCs who would not understand common. If your actor is misconfigured, that's not the module's fault.
2. It already does that.

A workaround for you would be to just run a script macro that adds 'common' to every actor in your world that doesn't already have it : 
```js
const updates = [];
for (const actor of game.actors.entities) {
   const langs = duplicate(getProperty(actor.data, "data.traits.languages.value") || [])
   if (!langs.includes("common")) { 
     langs.push("common")
     updates.push({_id: actor.data._id, "data.traits.languages.value": langs})
    }
}
Actor.update(updates)
```
