### ISSUE TITLE
Make it work with journals

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/fvtt-module-polyglot#6]
Journal owner could have a selection for the language, and if it's shown, anyone not speaking the language wouldn't be able to understand it

**Comment by trdischat** [comment]
As a refinement on this idea, allow strings within a journal entry to be tagged with a language. For example:

`On the mountainside, silver lines grow bright, outlining a door formed of two columns beneath an arch, with a star in the center.  Above the door is an inscription in ancient runes:
<span polyglot='Elvish'>The Doors of Durin - Lord of Moria. Speak friend and enter.</span>`

When displaying this journal entry to the players, a character that speaks Elvish would be able to read the inscription. Otherwise, polyglot displays the inscription as cryptic runes.

**Comment by kakaroto** [comment]
I love that idea :) I'm dreading doing a UI to let people use that functionality without html editing though...

**Comment by trdischat** [comment]
The existing journal system has a custom format for "secret" that uses a section tag.  Could you create another custom format for language using a span tag?  From a UI perspective, you just have a new formatting option in the menu for language.  I know, easier said than done.

**Comment by kakaroto** [comment]
Sure, but how to add a custom format to TinyMCE's interface, and how to have it ask for the language once selected (or have one different 'format' per language?). I haven't looked at all at how TinyMCE works so I don't know yet how easy it would be to extend it. It could be easy in which case, yeay!

**Comment by trdischat** [comment]
Thank you!!!  This is amazing.  I can see all sorts of applications for this.
